name: Deploy Terraform Infrastructure 02

on:
  push:
    branches:
      - main
    paths:
      - '02-devops-project/terraform/**'
      - '02-devops-project/app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: 02-devops-project/terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: 02-devops-project/terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: 02-devops-project/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: 02-devops-project/terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: 02-devops-project/terraform
        run: terraform apply -auto-approve tfplan

      - name: EC2 Instances initialization
        run: |
          echo "Waiting 120 seconds for Auto Scaling Group instances to boot up..."
          sleep 120

      - name: Generate Ansible Inventory
        working-directory: 02-devops-project/app/devops/scripts
        run: |
          chmod +x generate-inventory.sh
          ./generate-inventory.sh

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Set Correct Permissions for SSH Key
        working-directory: 02-devops-project/app/devops/ansible
        run: chmod 400 ansible-key.pem

      - name: Install NGINX
        working-directory: 02-devops-project/app/devops/ansible
        run: ansible-playbook -i inventory.ini install-nginx.yaml

      - name: Deploy Web Application
        working-directory: 02-devops-project/app/devops/ansible
        run: ansible-playbook -i inventory.ini deploy-app.yaml

      - name: Output Application Load Balancer URL
        working-directory: 02-devops-project/terraform
        run: |
          ALB_URL=$(terraform output -raw alb_dns_name)
          echo "🚀 AdviceMate is live at: http://$ALB_URL"

      - name: Upload SSH Key Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-private-key
          path: 02-devops-project/app/devops/ansible/ansible-key.pem
          retention-days: 1
